name: knit-kernmantle
version: '0.1.0.0'
synopsis: a minimal Rmarkdown sort-of-thing for haskell, by way of Pandoc.  Uses Kernmantle/Polysemy for effects handling.
description: ! 'knit-kernmantle is a beginning attempt at bringing some of the benefits
  of
  Rmarkdown to Haskell.
  It includes an effects stack
  (using polysemy,
  via <https://github.com/adamConnerSax/knit-haskell knit-haskell>,
  as a base for <https://github.com/YPares/kernmantle#readme kernmantle>,
  an arrow-inspired effects system.
  For similar functionality using just monadic effects use knit-haskell
  directly)
  which includes logging,
  a simplified interface to Pandoc and various writer-like effects to
  intersperse document building with regular code.
  Various helper functions are provided to simplify common operations,
  making it especially straightforward to build
  an HTML document from bits of markdown,
  latex and <http://hackage.haskell.org/package/lucid Lucid>
  or <http://hackage.haskell.org/package/blaze-html Blaze> html.
  Support is also included for including
  <http://hackage.haskell.org/package/hvega hvega> visualizations
  and diagrams from the <https://archives.haskell.org/projects.haskell.org/diagrams/
  diagrams>
  package.
  More information is available in the <https://github.com/adamConnerSax/knit-kernmantle/blob/master/Readme.md
  readme>.'
category: Text
author: Adam Conner-Sax
maintainer: adam_conner_sax@yahoo.com
copyright: 2020 Adam Conner-Sax
license: BSD3
github: adamConnerSax/knit-kernmantle
extra-source-files:
- ChangeLog.md
- Readme.md
library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - base >=4.12.0 && < 4.14
  - containers >=0.5.0 && <0.7
  - kernmantle >= 0.1.0 && < 0.2
  - knit-haskell >= 0.8.0 && < 0.9
  - text >=1.2.3 && <1.3
  - pandoc >=2.7.2 && <3.0
  - polysemy >= 1.2 && < 1.4
tests:
  SimpleExample:
    main: SimpleExample.hs
    other-modules: []
    source-dirs: examples
    ghc-options: -fplugin=Polysemy.Plugin
    dependencies:
    - base
    - knit-kernmantle
    - text
data-dir: data
data-files:
- knit-kernmantle-templates/*.html
- knit-kernmantle-css/*.css
- pandoc-data/data/templates/*.html4
- pandoc-data/data/templates/*.html5
- pandoc-data/data/templates/default.latex
- pandoc-data/data/templates/default.markdown
- pandoc-data/data/templates/default.commonmark
- pandoc-data/data/templates/default.haddock
